<?php

// builds js and css dependencies
$this->rcmUserBuildHtmlHead();
$this->headLink()->appendStylesheet('/modules/rcm-user/admin.css');
$this->headScript()->appendFile('/modules/rcm-user/admin-acl-app.js');

?>
<div ng-app="rcmuserAdminAclApp">
    <div class="rcmuser" ng-controller="rcmuserAdminAclRoles">

        <div class="container-fluid admin-acl">

            <!-- ADD RULE MODAL -->
            <script type="text/ng-template" id="addRule.html">
                <div class="rcmuser">
                    <div class="admin-acl">
                        <div class="modal-header">
                            <h3 class="modal-title">Add rule: </h3>
                        </div>
                        <div class="modal-body">
                            <div rcm-alerts="true" rcm-results="rcmUserHttp.alerts"
                                 alert-title-error="'An error occured:'"
                                 alert-title-success="'Success:'"></div>
                            <form name="addRuleForm" role="form">
                                <div class="form-group">
                                    <label for="rule">Rule: </label>
                                    <select class="form-control" name="rule"
                                            ng-model="ruleData.rule" required="true">
                                        <option selected="true"
                                                value="allow">allow
                                        </option>
                                        <!-- @todo Implement when ready
                                        <option value="deny">deny (unstable)</option>
                                        <option value="ignore">ignore</option>
                                        -->
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="roleId">Role: </label>

                                    <div name="roleId"
                                         class="roleId">{{ruleData.roleId}}
                                    </div>
                                </div>

                                <div class="form-group">

                                    <label for="resource">Resource: </label>
                                    <input
                                        class="form-control"
                                        name="resourceQuery"
                                        ng-focus="toggleDropdown($event, true)"
                                        ng-click="toggleDropdown($event, true)"
                                        ng-model="ruleData.resourceId"
                                        placeholder="Enter resource id"
                                        required="true"
                                        type="text"
                                        />

                                    <div class="list-dropdown"
                                         ng-show="status.isopen"
                                         ng-mouseleave="toggleDropdown($event, false)">
                                        <ul class="list-group">
                                            <li class="list-group-item"
                                                ng-repeat="resource in resources | resourceFilter:ruleData.resourceId">
                                                <a href
                                                   ng-click="ruleData.resourceId = resource.resource.resourceId; toggleDropdown($event, false)">
                                                    <div class="title">
                                                        {{resource.resource.name}}
                                                    </div>
                                                    <div>
                                                        ({{resource.resource.description}})
                                                    </div>
                                                    <div>
                                                        Resource: {{resource.resource.resourceId}}
                                                    </div>
                                                    <div>
                                                        NameSpace: {{resource.resourceNs}}
                                                    </div>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="privilege">Privilege: </label>
                                    <select class="form-control"
                                            name="privilege"
                                            ng-model="ruleData.privilege"
                                            required="true">
                                        <option selected="selected"
                                                value="">*ALL*
                                        </option>
                                        <option
                                            ng-repeat="priv in resources[ruleData.resourceId].resource.privileges"
                                            value="{{priv}}">{{priv}}
                                        </option>
                                    </select>
                                </div>
                            </form>

                        </div>

                        <div class="modal-footer">
                            <div class="loading"
                                 ng-show="rcmUserHttp.loading">LOADING...
                            </div>
                            <div ng-hide="rcmUserHttp.loading">
                                <button class="btn btn-primary btn-xs"
                                        ng-disabled="rcmUserHttp.loading"
                                        ng-click="addRule()">Add Rule
                                </button>
                                <button class="btn btn-warning btn-xs"
                                        ng-click="cancel()">
                                    Cancel
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </script>

            <!-- REMOVE RULE TEMPLATE -->
            <script type="text/ng-template" id="removeRule.html">
                <div class="rcmuser">
                    <div class="admin-acl">
                        <div class="modal-header">
                            <h3 class="modal-title">Are you sure you want to delete
                                rule: </h3>
                        </div>
                        <div class="modal-body">
                            <div rcm-alerts rcm-results="rcmUserHttp.alerts"
                                 alert-title-error="'An error occured:'"
                                 alert-title-success="'Success:'"></div>
                            <div>
                                <div class="rule">{{ruleData.rule}}</div>
                                <div>Role of:</div>
                                <div class="roleId">{{ruleData.roleId}}</div>
                            </div>
                            <div>
                                <div>Access to resource:</div>
                                <div class="resource-name">{{resourceData.resource.name}}
                                </div>
                            </div>
                            <div>
                                <div>For privilege:</div>
                                <div class="resource-privilege">{{(ruleData.privilege ||
                                    '*ALL*')}}
                                </div>
                            </div>
                            <div>
                                <div class="resource-details">
                                    {{resourceData.resource.description}}<br/><br/>
                                    Resource: {{resourceData.resource.resourceId}}<br/>
                                    NameSpace: {{resourceData.resourceNs}}
                                </div>
                            </div>

                        </div>
                        <div class="modal-footer">
                            <div class="loading"
                                 ng-show="rcmUserHttp.loading">LOADING...
                            </div>
                            <div ng-hide="rcmUserHttp.loading">
                                <button class="btn btn-primary btn-xs"
                                        ng-click="removeRule()">Remove Rule
                                </button>
                                <button class="btn btn-warning btn-xs"
                                        ng-click="cancel()">
                                    Cancel
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </script>

            <!-- ADD ROLE TEMPLATE -->
            <script type="text/ng-template" id="addRole.html">
                <div class="rcmuser">
                    <div class="admin-acl">
                        <div class="modal-header">
                            <h3 class="modal-title">Add role: </h3>
                        </div>
                        <div class="modal-body">
                            <div rcm-alerts rcm-results="rcmUserHttp.alerts"
                                 alert-title-error="'An error occured:'"
                                 alert-title-success="'Success:'"></div>
                            <form name="addRoleForm" role="form">
                                <div class="form-group">
                                    <label for="roleId">Role Id: </label>
                                    <input class="form-control" name="roleId"
                                           ng-model="roleData.roleId" required="true"
                                           type="text">
                                </div>
                                <div class="form-group">
                                    <label for="roleId">Parent Role: </label>
                                    <select class="form-control" name="parentRoleId"
                                            ng-model="roleData.parentRoleId"
                                            required="true">
                                        <option selected="selected"
                                                value="">-- root --
                                        </option>
                                        <option ng-repeat="roleObj in roles"
                                                value="{{roleObj.role.roleId}}">
                                            {{getNamespaceRepeatString(roleObj.roleNs,
                                            '..')}} {{roleObj.role.roleId}}
                                        </option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="description">Description: </label>
                                    <textarea
                                        class="form-control"
                                        name="description"
                                        ng-model="roleData.description"
                                        ng-required="true"
                                        minlength="5"
                                        ng-maxlength="255"
                                        required="true"
                                        value=""
                                        >
                                    </textarea>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <div class="loading"
                                 ng-show="rcmUserHttp.loading">LOADING...
                            </div>
                            <div ng-hide="rcmUserHttp.loading">
                                <button class="btn btn-primary btn-xs"
                                        ng-disabled="rcmUserHttp.loading"
                                        ng-click="addRole()">Add Role
                                </button>
                                <button class="btn btn-warning btn-xs"
                                        ng-click="cancel()">
                                    Cancel
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </script>

            <!-- EDIT ROLE TEMPLATE -->
            <script type="text/ng-template" id="editRole.html">
                <div class="rcmuser">
                    <div class="admin-acl">
                        <div class="modal-header">
                            <h3 class="modal-title">Edit role: </h3>
                        </div>
                        <div class="modal-body">
                            <div rcm-alerts rcm-results="rcmUserHttp.alerts"
                                 alert-title-error="'An error occured:'"
                                 alert-title-success="'Success:'"></div>
                            <!-- @todo create me
                            <form name="editRoleForm" role="form">
                                <div class="form-group">
                                    <label for="roleId">Role Id: </label>
                                    <input class="form-control" name="roleId" ng-model="roleData.roleId" required="true" type="text">
                                </div>
                                <div class="form-group">
                                    <label for="roleId">Parent Role: </label>
                                    <select class="form-control" name="parentRoleId" ng-model="roleData.parentRoleId" required="true">
                                        <option selected="selected" value="">-- choose parent role --</option>
                                        <option selected="selected" value="">*root*</option>
                                        <option ng-repeat="roleObj in roles" value="{{roleObj.role.roleId}}">{{roleObj.role.roleId}}</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="description">Description: </label>
                                    <textarea
                                        class="form-control"
                                        name="description"
                                        ng-model="roleData.description"
                                        ng-required="true"
                                        ng-minlength="5"
                                        ng-maxlength="255"
                                        required="true"
                                        >
                                    </textarea>
                                </div>
                            </form>

                        </div>
                        <div class="modal-footer">
                            <div class="loading" ng-show="rcmUserHttp.loading">LOADING...</div>
                            <div ng-hide="rcmUserHttp.loading">
                                <button class="btn btn-primary btn-xs" ng-disabled="rcmUserHttp.loading" ng-click="editRole()">Save Role</button>
                                <button class="btn btn-warning btn-xs" ng-click="cancel()">Cancel</button>
                            </div>
                        </div>
                        -->
                        </div>
                    </div>
            </script>

            <!-- REMOVE ROLE TEMPLATE -->
            <script type="text/ng-template" id="removeRole.html">
                <div class="rcmuser">
                    <div class="admin-acl">
                        <div class="modal-header">
                            <h3 class="modal-title">Are you sure you want to delete: </h3>
                        </div>
                        <div class="modal-body">
                            <div rcm-alerts rcm-results="rcmUserHttp.alerts"
                                 alert-title-error="'An error occured:'"
                                 alert-title-success="'Success:'"></div>
                            <div>
                                <div>Role:</div>
                                <div class="roleId">{{roleData.role.roleId}}</div>
                                <div>{{roleData.role.description}}</div>
                                <div>With parent:</div>
                                <div class="roleId">{{roleData.role.parentRoleId}}</div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <div class="loading"
                                 ng-show="rcmUserHttp.loading">LOADING...
                            </div>
                            <div ng-hide="loading">
                                <button class="btn btn-primary btn-xs"
                                        ng-disabled="rcmUserHttp.loading"
                                        ng-click="removeRole()">Remove Role
                                </button>
                                <button class="btn btn-warning btn-xs"
                                        ng-click="cancel()">
                                    Cancel
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </script>

            <div class="container-fluid">
                <h1>Access
                    <small>Control user roles and access</small>
                </h1>
                <p class="lead">Set up the user roles and access to resources.</p>
            </div>

            <form class="search-header form-horizontal" role="userSearch">
                <div class="form-group">
                    <!--<div class="col-sm-3">
                        <input
                            class="form-control input-sm"
                            name="roleSearch"
                            ng-model="roleQuery"
                            placeholder="search"
                            type="text"
                            />
                    </div>
                    -->
                    <div class="col-sm-offset-10 col-sm-2">
                        <button type="button" class="btn btn-primary btn-xs"
                                ng-click="openAddRole('sm', roles)"
                                ng-disabled="rcmUserHttp.loading">
                            <i class="glyphicon glyphicon-plus"></i> add role
                        </button>
                    </div>
                </div>
            </form>

           <div rcm-alerts rcm-results="rcmUserHttp.alerts"
                 alert-title-error="'An error occured:'"
                 alert-title-success="'Success:'"></div>

            <i class="glyphicon glyphicon-refresh loading"
               ng-class="{'active': rcmUserHttp.loading}"></i>

            <div class="container-fluid"
                 ng-hide="rcmUserHttp.alerts.results.length || rcmUserHttp.loading">

                <accordion close-others="oneAtATime">

                    <!-- + ROLE -->
                    <accordion-group is-open="isopen" heading="{{role.roleId}}"
                                     ng-repeat="roleData in roles">

                        <accordion-heading>
                            <div class="accordion-heading">
                                <span class="roleId" tooltip-placement="right"
                                      tooltip="This is a user role with roleId of &quot;{{roleData.role.roleId}}&quot;">{{levelRepeat(roleData.roleNs, '&#8901;&#8901;', '.')}} {{roleData.role.roleId}}
                                </span>
                                <i class="role-opener glyphicon"
                                   ng-class="{'glyphicon-chevron-down': isopen, 'glyphicon-chevron-right': !isopen}"></i>
                                <span class="role-actions pull-right">

                                </span>
                            </div>
                        </accordion-heading>
                        <section class="roleHeader">
                            <div class="roleDetails">
                                <div class="roleIdDetails">
                                    Role Id: {{roleData.role.roleId}}
                                </div>
                                <div class="roleDescription"
                                     ng-show="roleData.role.description">
                                    Description: {{roleData.role.description}}
                                </div>
                            </div>
                            <div class="">
                                <!-- @todo Implement when ready
                                <button type="button" class="btn btn-primary btn-xs" disabled="true" ng-click="openEditRole('sm', roleData)" ng-hide="roleData.role.isSuperAdminRole">
                                    <i class="glyphicon glyphicon-edit"></i> edit role
                                </button>
                                -->
                                <button type="button" class="btn btn-warning btn-xs"
                                        ng-click="openRemoveRole('sm', roleData)"
                                        ng-disabled="rcmUserHttp.loading"
                                        ng-hide="roleData.role.isSuperAdminRole">
                                    <i class="glyphicon glyphicon-minus"></i> remove role
                                </button>
                            </div>
                        </section>

                        <section class="ruleHeader">
                            <div class="ruleTitle">Rules:</div>
                        </section>

                        <!-- + RESOURCE -->
                        <div ng-hide="roleData.role.isSuperAdminRole"">
                            <div class="container-fluid admin-acl-resource-section"
                                 ng-repeat="ruleData in roleData.rules">

                                <div class="container-fluid">
                                    <div class="row">
                                        <div class="col-sm-9">
                                            <div>
                                                <span class="rule">{{ruleData.rule}}</span>
                                            </div>
                                            <div>Access to
                                                <span class="resource-name"
                                                      tooltip-placement="right"
                                                      tooltip-append-to-body="true"
                                                      tooltip-title="{{resources[ruleData.resourceId].resource.resourceId}}"
                                                      tooltip-html-unsafe="{{resources[ruleData.resourceId].resource.description}}<br/><br/>Resource: {{resources[ruleData.resourceId].resource.resourceId}}<br/>NameSpace: {{resources[ruleData.resourceId].resourceNs}}">{{resources[ruleData.resourceId].resource.name}}
                                                </span>
                                                <span>({{resources[ruleData.resourceId].resource.resourceId}})</span>
                                            </div>
                                            <div>For privilege
                                                <span class="resource-privilege">{{(ruleData.privilege || '* (ALL)')}}</span>
                                            </div>
                                        </div>

                                        <div class="col-sm-3">
                                            <div class="btn-group-vertical">
                                                <!-- @todo Implement when ready
                                                <button type="button" class="btn btn-primary btn-xs" disabled="true" ng-click="openEditRule('sm', ruleData)">
                                                    <i class="glyphicon glyphicon-edit"></i> edit rule
                                                </button>
                                                -->
                                                <button type="button"
                                                        class="btn btn-warning btn-xs"
                                                        ng-click="openRemoveRule('sm', ruleData, resources[ruleData.resourceId])"
                                                        ng-disabled="rcmUserHttp.loading">
                                                    <i class="glyphicon glyphicon-minus"></i>
                                                    remove rule
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div ng-hide="roleData.rules.length">
                                <div class="alert alert-warning">
                                    <i class="glyphicon glyphicon-warning-sign"></i>
                                    <span class="no-rules"
                                          ng-show="roleData.role.parentRoleId">No rules created, access rules inherited from {{roleData.role.parentRoleId}}.
                                    </span>
                                    <span class="no-rules"
                                          ng-hide="roleData.role.parentRoleId">No rules created.
                                    </span>
                                </div>
                            </div>

                            <div class="container-fluid admin-acl-resource-footer">
                                <div class="row">
                                    <div class="col-sm-2">
                                        <button type="button"
                                                class="btn btn-primary btn-xs"
                                                ng-click="openAddRule('', roleData, resources)"
                                                ng-disabled="rcmUserHttp.loading">
                                            <i class="glyphicon glyphicon-plus"></i> add
                                            rule
                                        </button>
                                    </div>
                                    <div class="col-sm-10">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div ng-show="roleData.role.isSuperAdminRole">
                            <div class="alert alert-info">
                                <i class="glyphicon glyphicon-info-sign"></i>
                                <span class="is-superadmin">This role is super admin. Role has full access and cannot be changed.</span>
                            </div>
                        </div>
                        <!-- + RESOURCE -->
                    </accordion-group>
                    <!-- - ROLE -->
                </accordion>
            </div>
        </div>
    </div>
</div>
